-- Test-only replica of the pre-existing Oracle tables queried by UserMapper.xml.
CREATE TABLE APP_USERS (
    USER_ID              VARCHAR2(100) PRIMARY KEY,
    PASSWORD_HASH        VARCHAR2(255) NOT NULL,
    PASSWORD_EXPIRY_DATE DATE
);

CREATE TABLE APP_USER_ROLES (
    USER_ID   VARCHAR2(100) NOT NULL REFERENCES APP_USERS (USER_ID),
    ROLE_NAME VARCHAR2(50)  NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_NAME)
);
